image: node:7.10-alpine

stages:
  - test
  - deploy

variables:
  S3_BUCKET_NAME: "dev.clai.io/cuest-web/"
  SLACK_WEBHOOK: "https://hooks.slack.com/services/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"

before_script:
   - which apk && apk update --quiet && apk upgrade --quiet && apk add --quiet git
   - git submodule sync --recursive
   - git submodule update --init --recursive
   - yarn install

build_job:
  stage: test
  script:
   - yarn run build

test_job:
  stage: test
  script:
   - yarn run test

deploy_job:
  stage: deploy
  environment: production
  only:
    - master
  script:
    - which apk && apk add --quiet py-pip
    - which pip && pip install --quiet awscli
    - yarn run build
    - aws s3 cp ./build s3://$S3_BUCKET_NAME --recursive
    - >
      curl -X POST
      --data-urlencode 'payload={"text": "Deployed! :muscle::skin-tone-6:"}'
      $SLACK_WEBHOOK
