image: node:7.10-alpine

stages:
  - build
  - test
  - deploy_prod
  - deploy_dev

variables:
  S3_DEV_BUCKET: "dev.clai.io/cuest-web/"
  S3_PROD_BUCKET: "app.cuest.io"
  SLACK_WEBHOOK: "https://hooks.slack.com/services/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"

before_script:
   - which apk && apk update --quiet && apk upgrade --quiet && apk add --quiet git
   - git submodule sync --recursive
   - git submodule update --init --recursive
   - yarn install

build_job:
  stage: build
  script:
   - yarn run build

test_job:
  stage: test
  script:
   - yarn run test

deploy_to_dev:
  stage: deploy_dev
  environment: development
  only:
    - development
  script:
    - which apk && apk add --quiet py-pip curl
    - which pip && pip install --quiet awscli
    - NODE_ENV=development yarn run build
    - aws s3 cp ./build s3://$S3_DEV_BUCKET --recursive
    - >
      curl -X POST
      --data-urlencode 'payload={"text": "Deployed to Dev! :muscle::skin-tone-6:"}'
      $SLACK_WEBHOOK

deploy_to_prod:
  stage: deploy_prod
  environment: production
  only:
    - master
  script:
    - which apk && apk add --quiet py-pip curl
    - which pip && pip install --quiet awscli
    - NODE_ENV=production yarn run build
    - aws s3 cp ./build s3://$S3_PROD_BUCKET --recursive
    - >
      curl -X POST
      --data-urlencode 'payload={"text": "Deployed to Prod! :muscle::skin-tone-6:"}'
      $SLACK_WEBHOOK
