image: node:6.9.4

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
   - npm install
   - npm build

test_job:
  stage: test
  script:
   - npm install
   - npm test

variables:
  S3_BUCKET_NAME: "dev.clai.io/culture-web-app/"
deploy_job:
  image: python:latest
  stage: deploy
  script:
    - npm install
    - npm build
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python get-pip.py
    - pip install awscli
    - aws s3 cp ./build s3://$S3_BUCKET_NAME --recursive
