image: node:7.10-alpine

stages:
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  S3_BUCKET_NAME: "dev.clai.io/cuest-web/"

build_job:
  stage: test
  script:
   - yarn install
   - yarn run build

test_job:
  stage: test
  script:
   - yarn install
   - yarn run test

deploy_job:
  stage: deploy
  environment: production
  only:
    - master
  script:
    - which apk && apk update --quiet && apk upgrade --quiet && apk add --quiet py-pip
    - which pip && pip install --quiet awscli
    - yarn install
    - yarn run build
    - aws s3 cp ./build s3://$S3_BUCKET_NAME --recursive
