image: node:6.9.4

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
   - npm install
   - npm build

test_job:
  stage: test
  script:
   - npm install
   - npm test

variables:
/"
deploy_job:
  stage: deploy
  script:
    - npm install
    - npm build
    - apt-get install python-pip
    - python get-pip.py
    - pip install awscli
    - aws s3 cp ./build s3://$S3_BUCKET_NAME --recursive
