// flow-typed signature: fb55f29a135e12712ad389d419e885ef
// flow-typed version: <<STUB>>/babel-preset-es2015-webpack_v6.4.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015-webpack/index' {
  declare module.exports: $Exports<'babel-preset-es2015-webpack'>;
}
declare module 'babel-preset-es2015-webpack/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-webpack'>;
}
