// flow-typed signature: 9aa9c2f07fc09c5e6cfbabc9ba677459
// flow-typed version: <<STUB>>/postcss-loader_v^1.2.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-loader/error' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-loader/error.js' {
  declare module.exports: $Exports<'postcss-loader/error'>;
}
declare module 'postcss-loader/index' {
  declare module.exports: $Exports<'postcss-loader'>;
}
declare module 'postcss-loader/index.js' {
  declare module.exports: $Exports<'postcss-loader'>;
}
