// flow-typed signature: f44841bc94a87dab0687405c186c9860
// flow-typed version: <<STUB>>/postcss-variables-loader_v^2.1.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-variables-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-variables-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-variables-loader/lib/index' {
  declare module.exports: any;
}

declare module 'postcss-variables-loader/lib/sync' {
  declare module.exports: any;
}

declare module 'postcss-variables-loader/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-variables-loader/lib/index.js' {
  declare module.exports: $Exports<'postcss-variables-loader/lib/index'>;
}
declare module 'postcss-variables-loader/lib/sync.js' {
  declare module.exports: $Exports<'postcss-variables-loader/lib/sync'>;
}
declare module 'postcss-variables-loader/lib/utils.js' {
  declare module.exports: $Exports<'postcss-variables-loader/lib/utils'>;
}
