// flow-typed signature: c8d6751b316cd1a1532945faee30a959
// flow-typed version: <<STUB>>/webpack-target-electron-renderer_v0.4.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-target-electron-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-target-electron-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-target-electron-renderer/index' {
  declare module.exports: $Exports<'webpack-target-electron-renderer'>;
}
declare module 'webpack-target-electron-renderer/index.js' {
  declare module.exports: $Exports<'webpack-target-electron-renderer'>;
}
